#index:
#    path: /
#    controller: App\Controller\DefaultController::index
admin:
  path: /admin
  controller: App\Controller\AdminController::admin
user:
  path: /user
  controller: App\Controller\UserController::user